= Kontrola obsahu

Obsahová kontrola

[[obs1]]
== obs1

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje atribut OBJID s neprázdnou hodnotou.
Kód:: obs1
Zdroj:: Bod 2.1. přílohy č. 3 NSESSS.
Popis chyby:: Chybí identifikátor datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs2]]
== obs2

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje atribut LABEL s hodnotou Datový balíček pro provedení skartačního řízení nebo Datový balíček pro předávání dokumentů a jejich metadat do archivu.
Kód:: obs2
Zdroj:: Bod 2.1. přílohy č. 3 NSESSS, navíc jsou přípustné i balíčky pro předání do archivu, v souladu s praxí NA ČR a shodně s pravidlem obs3 (Informační list NA, 2018, částka 2, č. 19/2018).
Popis chyby:: Uveden je chybně popis datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami)

[[obs3]]
== obs3

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje atribut LABEL s hodnotou Datový balíček pro předávání dokumentů a jejich metadat do archivu.
Kód:: obs3
Zdroj:: Bod 2.1. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis datového balíčku SIP.
Aktivní:: přejímka

[[obs4]]
== obs4

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje atribut xmlns:xsi s hodnotou http://www.w3.org/2001/XMLSchema-instance.
Kód:: obs4
Zdroj:: Bod 2.1. přílohy č. 3 NSESSS.
Popis chyby:: Uvedena je chybně adresa jmenného prostoru schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs9]]
== obs9

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje atribut xmlns:xlink s hodnotou http://www.w3.org/1999/xlink.
Kód:: obs9
Zdroj:: Bod 2.1. přílohy č. 3 NSESSS.
Popis chyby:: Uvedena je chybně adresa jmenného prostoru schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs10]]
== obs10

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje dětský element <mets:metsHdr>.
Kód:: obs10
Zdroj:: Bod 2.2. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (záhlaví) struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs11]]
== obs11

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje právě jeden dětský element <mets:dmdSec>.
Kód:: obs11
Zdroj:: Bod 2.6. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná (popisná) část struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs12]]
== obs12

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje alespoň jeden element <mets:amdSec>.
Kód:: obs12
Zdroj:: Bod 2.9. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (transakční protokol) struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs13]]
== obs13

[horizontal]

Pravidlo:: Element <mets:mets> obsahuje právě jeden dětský element <mets:structMap>.
Kód:: obs13
Zdroj:: Bod 2.2.17. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (strukturální mapa) struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs14]]
== obs14

[horizontal]

Pravidlo:: Element <mets:metsHdr> obsahuje atribut LASTMODDATE.
Kód:: obs14
Zdroj:: Bod 2.2. přílohy č. 3 NSESSS.
Popis chyby:: Chybí datum poslední úpravy datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs15]]
== obs15

[horizontal]

Pravidlo:: Element <mets:metsHdr> obsahuje atribut CREATEDATE.
Kód:: obs15
Zdroj:: Bod 2.2. přílohy č. 3 NSESSS.
Popis chyby:: Chybí datum vytvoření datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs16]]
== obs16

[horizontal]

Pravidlo:: Element <mets:metsHdr> obsahuje právě jeden element <mets:agent> s atributem TYPE s hodnotou ORGANIZATION.
Kód:: obs16
Zdroj:: Bod 2.3. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis původce.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs17]]
== obs17

[horizontal]

Pravidlo:: Element <mets:metsHdr> obsahuje alespoň jeden element <mets:agent> s atributem TYPE s hodnotou INDIVIDUAL.
Kód:: obs17
Zdroj:: Bod 2.3. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis původce.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs18]]
== obs18

[horizontal]

Pravidlo:: Každý element <mets:agent> obsahuje atribut ROLE s hodnotou CREATOR.
Kód:: obs18
Zdroj:: Bod 2.3. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis původce.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs19]]
== obs19

[horizontal]

Pravidlo:: Každý element <mets:agent> obsahuje atribut ID.
Kód:: obs19
Zdroj:: Bod 2.3. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis původce.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs20]]
== obs20

[horizontal]

Pravidlo:: Každý element <mets:agent> obsahuje právě jeden dětský element <mets:name> s neprázdnou hodnotou.
Kód:: obs20
Zdroj:: Bod 2.4. přílohy č. 3 NSESSS.
Popis chyby:: Chybí informace o původci.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs22]]
== obs22

[horizontal]

Pravidlo:: Element <mets:dmdSec> obsahuje právě jeden dětský element <mets:mdWrap>.
Kód:: obs22
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná (popisná) část struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs23]]
== obs23

[horizontal]

Pravidlo:: Element <mets:dmdSec> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut MDTYPEVERSION s hodnotou 3.0.
Kód:: obs23
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs24]]
== obs24

[horizontal]

Pravidlo:: Element <mets:dmdSec> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut OTHERMDTYPE s hodnotou NSESSS.
Kód:: obs24
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs25]]
== obs25

[horizontal]

Pravidlo:: Element <mets:dmdSec> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut MDTYPE s hodnotou OTHER.
Kód:: obs25
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs26]]
== obs26

[horizontal]

Pravidlo:: Element <mets:dmdSec> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut MIMETYPE s hodnotou text/xml.
Kód:: obs26
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs27]]
== obs27

[horizontal]

Pravidlo:: Element <mets:dmdSec> obsahuje v hierarchii dětských elementů <mets:mdWrap> právě jeden dětský element <mets:xmlData>.
Kód:: obs27
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná (popisná) část struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs28]]
== obs28

[horizontal]

Pravidlo:: Pokud neexistuje žádný element <nsesss:KrizovyOdkaz> s atributem pevny s hodnotou ano, potom element <mets:dmdSec> obsahuje v hierarchii dětských elementů <mets:mdWrap>, <mets:xmlData> právě jeden dětský element <nsesss:Dil>, <nsesss:Dokument> nebo <nsesss:Spis>.
Kód:: obs28
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS; příloha č. 2 NSESSS, ř. 20.
Popis chyby:: Datový balíček SIP neobsahuje díl, spis ani dokument.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs29]]
== obs29

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:KrizovyOdkaz> a obsahuje atribut pevny s hodnotou ano, potom pro každý jeho výskyt obsahuje element <mets:dmdSec> v hierarchii dětských elementů <mets:mdWrap>, <mets:xmlData> dětský element <nsesss:Dil> nebo <nsesss:Dokument> nebo <nsesss:Spis> se stejnou hodnotou v dětském elementu <nsesss:Identifikator> a v jeho atributu zdroj.
Kód:: obs29
Zdroj:: Bod 2.7. přílohy č. 3 NSESSS; příloha č. 2 NSESSS, ř. 20.
Popis chyby:: Chybí popis dílu, spisu nebo dokumentu, který je v datovém balíčku SIP připojen pevným křížovým odkazem.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs30]]
== obs30

[horizontal]

Pravidlo:: Každý element <mets:amdSec> obsahuje atribut ID.
Kód:: obs30
Zdroj:: Bod 2.9. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (transakční protokol) struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs31]]
== obs31

[horizontal]

Pravidlo:: Každý element <mets:amdSec> obsahuje právě jeden dětský element <mets:digiprovMD>.
Kód:: obs31
Zdroj:: Bod 2.10. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (transakční protokol) struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs33]]
== obs33

[horizontal]

Pravidlo:: Každý element <mets:digiprovMD> obsahuje právě jeden dětský element <mets:mdWrap>.
Kód:: obs33
Zdroj:: Bod 2.11. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (transakční protokol) struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs34]]
== obs34

[horizontal]

Pravidlo:: Každý element <mets:digiprovMD> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut MDTYPEVERSION s hodnotou 1.0.
Kód:: obs34
Zdroj:: Bod 2.11. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs35]]
== obs35

[horizontal]

Pravidlo:: Každý element <mets:digiprovMD> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut OTHERMDTYPE s hodnotou TP.
Kód:: obs35
Zdroj:: Bod 2.11. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs36]]
== obs36

[horizontal]

Pravidlo:: Každý element <mets:digiprovMD> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut MDTYPE s hodnotou OTHER.
Kód:: obs36
Zdroj:: Bod 2.11. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs37]]
== obs37

[horizontal]

Pravidlo:: Každý element <mets:digiprovMD> obsahuje v hierarchii dětských elementů <mets:mdWrap> atribut MIMETYPE s hodnotou text/xml.
Kód:: obs37
Zdroj:: Bod 2.11. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis schématu XML.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs38]]
== obs38

[horizontal]

Pravidlo:: Každý element <mets:digiprovMD> obsahuje v hierarchii dětských elementů <mets:mdWrap> právě jeden dětský element <mets:xmlData>.
Kód:: obs38
Zdroj:: Bod 2.12. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (transakční protokol) struktury datového balíčku SIP.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs39]]
== obs39

[horizontal]

Pravidlo:: Každý element <mets:digiprovMD> obsahuje v hierarchii dětských elementů <mets:mdWrap>, <mets:xmlData> právě jeden dětský element <tp:TransakcniLogObjektu>.
Kód:: obs39
Zdroj:: Bod 2.12. přílohy č. 3 NSESSS.
Popis chyby:: Datový balíček SIP neobsahuje transakční protokol.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs40]]
== obs40

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ne, obsahuje element <mets:mets> právě jeden dětský element <mets:fileSec>.
Kód:: obs40
Zdroj:: Bod 2.13. přílohy č. 3 NSESSS.
Popis chyby:: Chybí připojení komponent (počítačových souborů).
Aktivní:: skartační řízení (s komponentami), přejímka


[[obs41]]
== obs41

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element mets:file, každý obsahuje atribut MIMETYPE, jeho hodnota musí odpovídat pravidlům pro tvorbu označení MIMETYPE uvedených na https://www.iana.org/assignments/media-types/media-types.xhtml a musí odpovídat typu referencovaného souboru.
Kód:: obs41
Zdroj:: Bod 2.15. přílohy č. 3 NSESSS.
Popis chyby:: Atribut MIMETYPE elementu mets:file neobsahuje správnou hodnotu nebo je prázdný.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka


[[obs43a]]
== obs43a

[horizontal]

Pravidlo:: Pokud existuje element <mets:fileSec>, obsahuje právě jeden dětský element <mets:fileGrp>.
Kód:: obs43a
Zdroj:: Bod 2.14. přílohy č. 3 NSESSS.
Popis chyby:: Chybí připojení komponent (počítačových souborů) nebo je špatně strukturováno.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs44]]
== obs44

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:file>, každý obsahuje atribut DMDID s hodnotou uvedenou v atributu ID jakéhokoli elementu <nsesss:Komponenta>, přičemž právě jedna hodnota atributu DMDID odpovídá právě jedné hodnotě atributu ID.
Kód:: obs44
Zdroj:: Bod 2.15. přílohy č. 3 NSESSS.
Popis chyby:: Chybí provázání komponenty (počítačového souboru) s popisnou částí.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs45]]
== obs45

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:file>, každý obsahuje atribut MIMETYPE s hodnotou identifikace souborového formátu příslušné komponenty.
Kód:: obs45
Zdroj:: Bod 2.15. přílohy č. 3 NSESSS.
Popis chyby:: Komponenta (počítačový soubor) má uvedený chybný datový formát.
Aktivní:: skartační řízení (s komponentami), přejímka

Pro ověření formátu příslušné komponenty je standardně využíván nástroj Apache Tika. Pomocí konfigurace je 
možné alternativně použít SiegFried, viz xref:pouziti.adoc#ZafSystParametry[systémové parametry].


[[obs46]]
== obs46

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:file>, každý obsahuje atribut CHECKSUMTYPE hodnotu SHA-256 nebo SHA-512.
Kód:: obs46
Zdroj:: Bod 2.15. přílohy č. 3 NSESSS.
Popis chyby:: Chybí popis pro ověření celistvosti komponenty (počítačového souboru) nebo je chybně uveden.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs47]]
== obs47

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:file>, každý obsahuje atribut CHECKSUM s hodnotou kontrolního součtu příslušné komponenty podle kryptografického algoritmu uvedeného v atributu CHECKSUMTYPE.
Kód:: obs47
Zdroj:: Bod 2.15. přílohy č. 3 NSESSS.
Popis chyby:: Celistvost komponenty (počítačového souboru) je narušena nebo chybí možnost jejího ověření.
Aktivní:: skartační řízení (s komponentami), přejímka

[[obs48]]
== obs48

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:file>, každý obsahuje atribut SIZE s hodnotou velikosti příslušné komponenty v bytech.
Kód:: obs48
Zdroj:: Bod 2.15. přílohy č. 3 NSESSS.
Popis chyby:: Chybí velikost komponenty (počítačového souboru) nebo je uvedena chybně.
Aktivní:: skartační řízení (s komponentami), přejímka

[[obs49]]
== obs49

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:file>, každý obsahuje atribut CREATED.
Kód:: obs49
Zdroj:: Bod 2.15. přílohy č. 3 NSESSS.
Popis chyby:: Chybí datum vytvoření komponenty (počítačového souboru).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs50]]
== obs50

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:file>, každý obsahuje právě jeden dětský element <mets:FLocat>.
Kód:: obs50
Zdroj:: Bod 2.16. přílohy č. 3 NSESSS.
Popis chyby:: Chybí připojení komponenty (počítačového souboru) do datového balíčku SIP nebo je provedeno chybně.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs51]]
== obs51

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:FLocat>, každý obsahuje atribut xlink:type s hodnotou simple.
Kód:: obs51
Zdroj:: Bod 2.16. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis odkazu na komponentu (počítačový soubor).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs52]]
== obs52

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:FLocat>, každý obsahuje atribut xlink:href s hodnotou, která odpovídá relativní cestě odkazu jakékoli komponenty uložené ve složce komponenty, přičemž právě jedna hodnota atributu xlink:href odpovídá relativní cestě odkazu právě jedné komponenty.
Kód:: obs52
Zdroj:: Bod 2.16. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis odkazu na komponentu (počítačový soubor).
Aktivní:: skartační řízení (s komponentami), přejímka

[[obs53]]
== obs53

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:FLocat>, každý obsahuje atribut LOCTYPE s hodnotou URL.
Kód:: obs53
Zdroj:: Bod 2.16. přílohy č. 3 NSESSS.
Popis chyby:: Uveden je chybně popis odkazu na komponentu (počítačový soubor).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs54]]
== obs54

[horizontal]

Pravidlo:: Pokud neexistuje žádný element <nsesss:KrizovyOdkaz> s atributem pevny s hodnotou ano, potom každý element <mets:div> obsahuje dětský element podle struktury entit/objektů (od spisového plánu po komponentu) v sekci dmdSec s atributem TYPE s hodnotou příslušné entity/objektu a s atributem DMDID s hodnotou příslušné entity/objektu v atributu ID a s atributem ADMID s hodnotou, která odpovídá hodnotě atributu ID příslušné entity/objektu v sekci amdSec (entita/objekt v hierarchii dětských elementů <mets:digiprovMD>, <mets:mdWrap>, <mets:xmlData>, <tp:TransakcniLogObjektu>, <tp:TransLogInfo>, <tp:Objekt>, <tp:Identifikator>, <tns:HodnotaID> a <tns:ZdrojID> odpovídá v hodnotách hodnotám elementu <nsesss:Identifikator> a jeho atributu zdroj příslušné entity/objektu v sekci dmdSec).
Kód:: obs54
Zdroj:: Bod 2.17 a 2.18. přílohy č. 3 NSESSS; Informační list NA, roč. 2018, čá. 2, příloha k č. 20/2018 (20.3).
Popis chyby:: Chybí spisový plán, věcná skupina, typový spis, součást, díl, spis, dokument nebo komponenta ve strukturální mapě a jejich provázání na transakční protokol.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs54]]
== obs54

[horizontal]

Pravidlo:: Každý element mets:div obsahuje dětský element podle struktury entit/objektů (od spisového plánu po komponentu) v sekci dmdSec s atributem TYPE s hodnotou příslušné entity/objektu a s atributem DMDID s hodnotou příslušné entity/objektu v atributu ID a s atributem ADMID s hodnotou, která odpovídá hodnotě atributu ID příslušné entity/objektu v sekci amdSec (entita/objekt v hierarchii dětských elementů mets:digiprovMD, mets:mdWrap, mets:xmlData, tp:TransakcniLogObjektu, tp:TransLogInfo, tp:Objekt, tp:Identifikator, tns:HodnotaID a tns:ZdrojID odpovídá v hodnotách hodnotám elementu nsesss:Identifikator a jeho atributu zdroj příslušné entity/objektu v sekci dmdSec). Uvedená entita/objekt je v sekci dmdSec, amdSec a structMap uvedena právě jednou. Pokud existuje jakýkoli element nsesss:KrizovyOdkaz a obsahuje atribut pevny s hodnotou ano, potom je entita/objekt typu součást, typový spis, věcná skupina nebo spisový plán v sekci dmdSec uvedená multiplicitně. V takovém případě je stejná entita/objekt uvedena v sekci structMap právě jednou (atribut DMDID obsahuje ID libovolného výskytu příslušné entity/objektu).
Kód:: obs54
Zdroj:: Bod 2.17 a 2.18. přílohy č. 3 NSESSS; Informační list NA, roč. 2018, čá. 2, příloha k č. 20/2018 (20.3).
Popis chyby:: Chybí spisový plán, věcná skupina, typový spis, součást, díl, spis, dokument nebo komponenta ve strukturální mapě a jejich provázání na transakční protokol.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs55]]
== obs55

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:div> s atributem TYPE s hodnotou komponenta, každý obsahuje právě jeden element <mets:fptr>.
Kód:: obs55
Zdroj:: Bod 2.19. přílohy č. 3 NSESSS.
Popis chyby:: Chybí povinná část (strukturální mapa) struktury datového balíčku SIP.
Aktivní:: skartační řízení (s komponentami), přejímka

[[obs56]]
== obs56

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <mets:fptr>, každý obsahuje atribut FILEID s hodnotou, která odpovídá hodnotě atributu ID elementu <mets:file> příslušné komponenty. Příslušnost vyjadřuje stejná hodnota atributu DMDID rodičovského elementu <mets:div> a elementu <mets:file>.
Kód:: obs56
Zdroj:: Bod 2.19. přílohy č. 3 NSESSS.
Popis chyby:: Není v souladu provázání komponent (počítačových souborů) mezi částí počítačových souborů a strukturální mapou.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs57]]
== obs57

[horizontal]

Pravidlo:: Jakýkoli element <nsesss:Identifikator> obsahuje neprázdnou hodnotu.
Kód:: obs57
Zdroj:: Příloha č. 2 NSESSS, ř. 123.
Popis chyby:: Není uveden identifikátor.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs58]]
== obs58

[horizontal]

Pravidlo:: Jakýkoli element <nsesss:Identifikator> obsahuje atribut zdroj s neprázdnou hodnotu.
Kód:: obs58
Zdroj:: Příloha č. 2 NSESSS, ř. 288.
Popis chyby:: Není uveden zdroj identifikátoru.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs59]]
== obs59

[horizontal]

Pravidlo:: Žádná entita (od spisového plánu po dokument) nebo objekt <nsesss:Komponenta>, <nsesss:BezpecnostniKategorie>, <nsesss:SkartacniRezim> nebo <nsesss:TypDokumentu> neobsahuje stejné hodnoty elementu <nsesss:Identifikator> a jeho atributu zdroj a současně odlišné hodnoty v ostatních elementech, jako má jiná entita nebo objekt uvedeného typu, kromě atributu ID uvedené entity.
Kód:: obs59
Zdroj:: Příloha č. 2 NSESSS, ř. 123.
Popis chyby:: Uveden je vícekrát stejný spisový plán, věcná skupina, typový spis, součást, díl, spis, dokument, komponenta, bezpečnostní kategorie, skartační režim nebo typ dokumentu nebo je vícekrát použit stejný identifikátor.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs60]]
== obs60

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ne, obsahuje element <nsesss:Dokument> dětský element <nsesss:Komponenty>.
Kód:: obs60
Zdroj:: Příloha č. 2 NSESSS, ř. 45.
Popis chyby:: Chybí popis komponenty (počítačového souboru) dokumentu v digitální podobě.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs61]]
== obs61

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ano a současně element <nsesss:EvidencniUdaje> obsahuje v dětském elementu <nsesss:Puvod> element <nsesss:DorucenyDokument>, potom je v posledním uvedeném elementu uveden dětský element <nsesss:DoruceneMnozstvi> s neprázdnou hodnotou.
Kód:: obs61
Zdroj:: Příloha č. 2 NSESSS, ř. 365.
Popis chyby:: Chybí doručené množství dokumentu v analogové podobě.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs61a]]
== obs61a

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ano a současně element <nsesss:EvidencniUdaje> obsahuje v dětském elementu <nsesss:Puvod> element <nsesss:VlastniDokument>, potom je v posledním uvedeném elementu uveden dětský element <nsesss:VytvoreneMnozstvi> s neprázdnou hodnotou.
Kód:: obs61a
Zdroj:: Příloha č. 2 NSESSS, ř. 1208.
Popis chyby:: Chybí množství vlastního dokumentu v analogové podobě.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs62]]
== obs62

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Jazyk>, každý obsahuje pouze hodnoty uvedené v číselníku ISO 639-2:1998 uvedeném na URL: http://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt.
Kód:: obs62
Zdroj:: Příloha č. 2 NSESSS, ř. 132.
Popis chyby:: Uveden je chybně jazyk dokumentu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs63]]
== obs63

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Vyrizeni> nebo element <nsesss:VyrizeniUzavreni> obsahuje element <nsesss:Zpusob> s hodnotou jiný způsob, potom je na stejné úrovni posledního uvedeného elementu uveden dětský element <nsesss:Oduvodneni> s neprázdnou hodnotou.
Kód:: obs63
Zdroj:: Příloha č. 2 NSESSS, ř. 1270.
Popis chyby:: Chybí odůvodnění vyřízení jiným způsobem.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs64]]
== obs64

[horizontal]

Pravidlo:: Pokud je základní entitou dokument (<nsesss:Dokument>), potom v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Vyrazovani>, <nsesss:DataceVyrazeni> je součet hodnoty elementu <nsesss:RokSpousteciUdalosti>, 1 a hodnoty elementu <nsesss:SkartacniLhuta> uvedeného v rodičovském elementu <nsesss:SkartacniRezim> menší nebo roven aktuálnímu roku.
Kód:: obs64
Zdroj:: § 15 odst. 4 vyhlášky č. 259/2012 Sb.
Popis chyby:: Uveden je chybně rok skartační operace u dokumentu (počítá se jako rok spouštěcí události + 1 + skartační lhůta).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka
Vysvětlení:: Ověření u SIPů, kde je základní entitou dokument, že je možné skartační řízení realizovat dle nastavených skartačních lhůt 
ve vztahu k dataci vzniku dokumentu.

[[obs65]]
== obs65

[horizontal]

Pravidlo:: Pokud je základní entitou díl (<nsesss:Dil>) nebo spis (<nsesss:Spis>), potom v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Vyrazovani>, <nsesss:DataceVyrazeni> je součet hodnoty elementu <nsesss:RokSpousteciUdalosti>, 1 a hodnoty elementu <nsesss:SkartacniLhuta> uvedeného v rodičovském elementu <nsesss:SkartacniRezim> menší nebo roven aktuálnímu roku. Pro všechny entity dokument (<nsesss:Dokument>) dále platí, že součet hodnoty elementu <nsesss:DatumDoruceni> nebo <nsesss:DatumVytvoreni> (v závislosti na tom, zda jde o doručený nebo vlastní dokument), 1 a hodnoty elementu <nsesss:SkartacniLhuta> je menší nebo roven aktuálnímu roku.
Kód:: obs65
Zdroj:: § 15 odst. 5 vyhlášky č. 259/2012 Sb.
Popis chyby:: Uveden je chybně rok skartační operace u dílu nebo spisu (počítá se jak podle roku spouštěcí události + 1 + skartační lhůta, tak podle roku skartační operace u dokumentů - záleží na tom, co je vyšší).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka
Vysvětlení:: Ověření u SIPů, kde je základní spis nebo díl, že je možné skartační řízení realizovat dle nastavených skartačních lhůt 
ve vztahu k dataci vzniku příslušné základní entity. Současně se provede kontrola všech dokumentů, že je opět u nich dle lhůt možné realizovat skartační řízení.


[[obs67]]
== obs67

[horizontal]

Pravidlo:: Pokud je základní entitou díl (<nsesss:Dil>) nebo spis (<nsesss:Spis>), potom v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Vyrazovani>, <nsesss:SkartacniRezim> obsahuje element <nsesss:SkartacniZnak> hodnotu, která je rovna nejvyššímu skartačnímu znaku dětské entity dokument (<nsesss:Dokument>), přičemž priorita skartačních znaků od nejvyšší po nejnižší je v pořadí A, V, S.
Kód:: obs67
Zdroj:: § 15 odst. 5 vyhlášky č. 259/2012 Sb.
Popis chyby:: Uveden je chybně skartační znak u dílu nebo spisu (stanovuje se podle nejvyššího skartačního znaku dokumentu).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs68]]
== obs68

[horizontal]

Pravidlo:: Každá entita věcná skupina (<nsesss:VecnaSkupina>), která je rodičovskou entitou spisu (<nsesss:Spis>) nebo dokumentu (<nsesss:Dokument>), obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Vyrazovani> element <nsesss:SkartacniRezim>.
Kód:: obs68
Zdroj:: § 15 odst. 2 vyhlášky č. 259/2012 Sb.; příloha č. 2 NSESSS, ř. 1250.
Popis chyby:: Chybí skartační režim věcné skupiny.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka


[[obs69]]
== obs69

[horizontal]

Pravidlo:: Pokud je základní entitou dokument (<nsesss:Dokument>), potom její element <nsesss:EvidencniUdaje> obsahuje dětský element <nsesss:Vyrizeni>.
Kód:: obs69
Zdroj:: Příloha č. 2 NSESSS, ř. 421.
Popis chyby:: Chybí vyřízení dokumentu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs70]]
== obs70

[horizontal]

Pravidlo:: Jakýkoli element <nsesss:Identifikator> není opakovatelný, pokud se nenachází v hierarchii elementů <nsesss:Komponenta>, <nsesss:EvidencniUdaje> a <nsesss:Identifikace>.
Kód:: obs70
Zdroj:: Příloha č. 2 NSESSS, ř. 497.
Popis chyby:: Uveden je chybně identifikátor věcné skupiny, typového spisu, součásti, dílu, spisu nebo dokumentu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs71]]
== obs71

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:DatumOtevreni>, obsahuje stejnou nebo menší hodnotu, než je hodnota elementu <nsesss:DatumUzavreni>, pokud poslední uvedený element existuje uvnitř rodičovského elementu <nsesss:Manipulace>.
Kód:: obs71
Zdroj:: null
Popis chyby:: Není v souladu datum otevření a datum uzavření spisového plánu, věcné skupiny, typového spisu, součásti, dílu nebo spisu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs72]]
== obs72

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:CasPouziti>, každý obsahuje atribut datum.
Kód:: obs72
Zdroj:: § 4 odst. 7 písm. b) vyhlášky č. 259/2012 Sb.
Popis chyby:: Chybí strojový zápis času opatření komponenty (počítačového souboru) elektronickým podpisem, elektronickou značkou nebo časovým razítkem.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs73]]
== obs73

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:CasOvereni>, každý obsahuje atribut datum.
Kód:: obs73
Zdroj:: § 4 odst. 7 písm. g) vyhlášky č. 259/2012 Sb.
Popis chyby:: Chybí strojový zápis času ověření elektronického podpisu, elektronické značky nebo časového razítka.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs74]]
== obs74

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:PosuzovanyOkamzik>, každý obsahuje atribut datum.
Kód:: obs74
Zdroj:: § 4 odst. 7 písm. f) vyhlášky č. 259/2012 Sb.
Popis chyby:: Chybí strojový zápis času, k němuž je vztaženo posuzování platnosti elektronického podpisu, elektronické značky nebo časového razítka.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs75]]
== obs75

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Platnost>, v každém obsahuje jeho dětský element <nsesss:PlatnostOd> stejnou nebo menší hodnotu, než je hodnota elementu <nsesss:PlatnostDo>.
Kód:: obs75
Zdroj:: null
Popis chyby:: Není v souladu rozsah platnosti certifikátu elektronického podpisu, elektronické značky nebo časového razítka.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs76]]
== obs76

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ano, potom rodičovské entity obsahují v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> se stejnou hodnotou.
Kód:: obs76
Zdroj:: Příloha č. 2 NSESSS, ř. 616.
Popis chyby:: Uvedeno je chybně u věcné skupiny, typového spisu, součásti, dílu nebo spisu, že neobsahují dokumenty v analogové podobě.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs77]]
== obs77

[horizontal]

Pravidlo:: Pokud základní entita obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ano, potom obsahuje v hierarchii dětských elementů <nsesss:Vyrazovani> a <nsesss:SkartacniRizeni> element <nsesss:Mnozstvi> s neprázdnou hodnotou.
Kód:: obs77
Zdroj:: Příloha č. 2 NSESSS, ř. 1006.
Popis chyby:: Chybí množství dílu, spisu nebo dokumentu v analogové podobě.
Aktivní:: přejímka

[[obs78]]
== obs78

[horizontal]

Pravidlo:: Element <nsesss:SkartacniRizeni> je uveden pouze v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Vyrazovani> základní entity.
Kód:: obs78
Zdroj:: Příloha č. 2 NSESSS, ř. 1228.
Popis chyby:: Chybí informace o skartačním řízení.
Aktivní:: přejímka

[[obs79]]
== obs79

[horizontal]

Pravidlo:: V elementu <nsesss:SkartacniRizeni> obsahuje element <nsesss:Datum> hodnotu, v níž je uvedený rok větší nebo roven hodnotě uvedené v elementu <nsesss:RokSkartacniOperace> uvnitř rodičovského elementu <nsesss:DataceVyrazeni> stejné entity.
Kód:: obs79
Zdroj:: null
Popis chyby:: Není v souladu datum skartačního řízení a roku skartační operace.
Aktivní:: přejímka

[[obs80]]
== obs80

[horizontal]

Pravidlo:: V jakémkoli elementu <nsesss:SkartacniRizeni> obsahuje element <nsesss:Datum> hodnotu, která je menší nebo rovna aktuálnímu roku.
Kód:: obs80
Zdroj:: § 20 odst. 1 vyhlášky č. 259/2012 Sb.
Popis chyby:: Uvedeno je chybně datum skartačního řízení (uváděný rok ještě nenadešel).
Aktivní:: přejímka

[[obs81]]
== obs81

[horizontal]

Pravidlo:: Pokud je v jakémkoli elementu <nsesss:UrceneCasoveObdobi> uveden dětský element <nsesss:DatumDo>, potom je jeho hodnota větší než <nsesss:DatumOd>.
Kód:: obs81
Zdroj:: null
Popis chyby:: Není v souladu rozsah určeného časového období.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs82]]
== obs82

[horizontal]

Pravidlo:: Pokud je v jakémkoli elementu <nsesss:UrceneCasoveObdobi> uveden dětský element <nsesss:MesicDo>, potom je jeho hodnota větší než <nsesss:MesicOd>.
Kód:: obs82
Zdroj:: null
Popis chyby:: Není v souladu rozsah určeného časového období.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs83]]
== obs83

[horizontal]

Pravidlo:: Pokud je v jakémkoli elementu <nsesss:UrceneCasoveObdobi> uveden dětský element <nsesss:RokDo>, potom je jeho hodnota větší než <nsesss:RokOd>.
Kód:: obs83
Zdroj:: null
Popis chyby:: Není v souladu rozsah určeného časového období.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs84]]
== obs84

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Vyrizeni> a obsahuje element <nsesss:Zpusob> s hodnotou jiný způsob, potom je na stejné úrovni posledního uvedeného elementu uveden dětský element <nsesss:ObsahVyrizeni> s neprázdnou hodnotou.
Kód:: obs84
Zdroj:: Příloha č. 2 NSESSS, ř. 1265.
Popis chyby:: Chybí obsah vyřízení jiným způsobem.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs85]]
== obs85

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ano, potom element <nsesss:Manipulace> obsahuje dětský element <nsesss:UkladaciJednotka> s neprázdnou hodnotou.
Kód:: obs85
Zdroj:: Příloha č. 2 NSESSS, ř. 1352.
Popis chyby:: Chybí ukládací jednotka dokumentu v analogově podobě.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs86]]
== obs86

[horizontal]

Pravidlo:: Pokud je základní entitou dokument (<nsesss:Dokument>), obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> element <nsesss:MaterskeEntity>.
Kód:: obs86
Zdroj:: Příloha č. 2 NSESSS, ř. 1397.
Popis chyby:: Chybí zatřídění dokumentu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs87]]
== obs87

[horizontal]

Pravidlo:: Pokud existuje element <nsesss:Vyrizeni> a obsahuje dětský element <nsesss:DatumOdeslani>, pak současně obsahuje i element <nsesss:Prijemce>. Pravidlo se uplatňuje i obráceně - v případě uvedení elementu <nsesss:Prijemce> je uveden i element <nsesss:DatumOdeslani>.
Kód:: obs87
Zdroj:: Příloha č. 2 NSESSS, ř. 1471 a 1481.
Popis chyby:: Chybí příjemce nebo datum odeslání dokumentu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs88]]
== obs88

[horizontal]

Pravidlo:: Pokud element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ano a současně element <nsesss:Vyrizeni> obsahuje dětský element <nsesss:DatumOdeslani>, pak element <nsesss:Vyrizeni> obsahuje element <nsesss:OdeslaneMnozstvi> s neprázdnou hodnotou.
Kód:: obs88
Zdroj:: Příloha č. 2 NSESSS, ř. 1476.
Popis chyby:: Chybí množství odeslaného dokumentu v analogové podobě.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka


[[obs92]]
== obs92

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Identifikator> s atributem zdroj s hodnotou IČ nebo IČO, hodnota obsahuje číslo o osmi číslicích, přičemž vážený součet prvních sedmi číslic má po dělení jedenácti zbytek, který po odečtení od 11 a následném vydělení 10 má zbytek roven poslední číslici.
Kód:: obs92
Zdroj:: null
Popis chyby:: Chybně je uvedeno IČO subjektu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs93]]
== obs93

[horizontal]

Pravidlo:: Jakýkoli element <nsesss:Nazev> obsahuje neprázdnou hodnotu.
Kód:: obs93
Zdroj:: Příloha č. 2 NSESSS, ř. 167.
Popis chyby:: Není uveden název.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs93a]]
== obs93a

[horizontal]

Pravidlo:: Každá entita věcná skupina (<nsesss:VecnaSkupina>), jejíž rodičovská entita je spisový plán (<nsesss:SpisovyPlan>), obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> elementy <nsesss:JednoduchySpisovyZnak> a <nsesss:PlneUrcenySpisovyZnak> se stejnými hodnotami.
Kód:: obs93a
Zdroj:: Požadavek 3.1.30 NSESSS.
Popis chyby:: Chybně jsou uvedeny spisové znaky.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs94]]
== obs94

[horizontal]

Pravidlo:: Každá entita vyjma jakéhokoli spisového plánu (<nsesss:SpisovyPlan>) obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> element <nsesss:PlneUrcenySpisovyZnak> s hodnotou, jejíž poslední část je stejná jako hodnota elementu <nsesss:JednoduchySpisovyZnak>.
Kód:: obs94
Zdroj:: Požadavek 3.1.30 NSESSS.
Popis chyby:: Chybně jsou uvedeny spisové znaky.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs95]]
== obs95

[horizontal]

Pravidlo:: Každá entita věcná skupina (<nsesss:VecnaSkupina>) nebo součást (<nsesss:Soucast>), která se nachází v rodičovské entitě věcná skupina (<nsesss:VecnaSkupina>) nebo typový spis (<nsesss:TypovySpis>), obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> element <nsesss:PlneUrcenySpisovyZnak> s hodnotou obsahující hodnotu elementu <nsesss:PlneUrcenySpisovyZnak> rodičovské entity, oddělovač a hodnotu elementu <nsesss:JednoduchySpisovyZnak> výchozí entity.
Kód:: obs95
Zdroj:: Požadavek 3.1.30 NSESSS.
Popis chyby:: Chybně jsou uvedeny spisové znaky.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs96]]
== obs96

[horizontal]

Pravidlo:: Každá základní entita a každá entita typový spis (<nsesss:TypovySpis>) obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> elementy <nsesss:JednoduchySpisovyZnak> a <nsesss:PlneUrcenySpisovyZnak> se stejnými hodnotami, jaké obsahují v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> elementy <nsesss:JednoduchySpisovyZnak> a <nsesss:PlneUrcenySpisovyZnak> rodičovské entity věcná skupina (<nsesss:VecnaSkupina>) nebo součást (<nsesss:Soucast>).
Kód:: obs96
Zdroj:: § 14 odst. 4 vyhlášky č. 259/2012 Sb.
Popis chyby:: Chybně jsou uvedeny spisové znaky.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs97]]
== obs97

[horizontal]

Pravidlo:: Pokud existuje více než jedna základní entita, všechny obsahují v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> elementy <nsesss:JednoduchySpisovyZnak> a <nsesss:PlneUrcenySpisovyZnak> se stejnými hodnotami.
Kód:: obs97
Zdroj:: Požadavek 3.1.34 NSESSS.
Popis chyby:: Chybně jsou uvedeny spisové znaky.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs98]]
== obs98

[horizontal]

Pravidlo:: Pokud je základní entitou díl (<nsesss:Dil>) nebo spis (<nsesss:Spis>), obsahují v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> elementy <nsesss:JednoduchySpisovyZnak> a <nsesss:PlneUrcenySpisovyZnak> se stejnými hodnotami, jaké obsahují v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Trideni> elementy <nsesss:JednoduchySpisovyZnak> a <nsesss:PlneUrcenySpisovyZnak> jakékoli dětské entity dokument (<nsesss:Dokument>).
Kód:: obs98
Zdroj:: § 14 odst. 4 vyhlášky č. 259/2012 Sb.
Popis chyby:: Chybně jsou uvedeny spisové znaky.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs99]]
== obs99

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ne a zároveň obsahuje element <nsesss:Komponenty>, ze všech dětských elementů <nsesss:Komponenta>, který obsahuje atribut forma_uchovani s hodnotou originál nebo originál ve výstupním datovém formátu a současně atribut verze s hodnotou nejvyššího čísla verze, potom jakýkoli element <mets:file>, který obsahuje atribut DMDID s hodnotou uvedenou v atributu ID jakéhokoli elementu <nsesss:Komponenta> příslušné komponenty a dále obsahuje atribut MIMETYPE s hodnotou application/pdf, reprezentuje příslušnou komponentu ve shodě s normou PDF/A. Kontrola se neprovádí, pokud byla základní entita vyřízena/uzavřena do 31. 7. 2012 včetně.
Kód:: obs99
Zdroj:: § 23 odst. 2 vyhlášky č. 259/2012 Sb.; Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Komponenta (počítačový soubor) v datovém formátu PDF není ve výstupním datovém formátu.
Aktivní:: skartační řízení (s komponentami), přejímka

[[obs100]]
== obs100

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Komponenty>, všechny dětské elementy <nsesss:Komponenta> obsahují v atributu poradi hodnotu, která společně tvoří vzestupnou a souvislou řadu přirozených čísel počínaje 1, přičemž čísla se mohou opakovat a úvodní nuly se ignorují.
Kód:: obs100
Zdroj:: Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Uvedeno je chybně pořadí komponent (počítačových souborů).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs101]]
== obs101

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Komponenty>, všechny dětské elementy <nsesss:Komponenta> se stejnou hodnotou atributu poradi obsahují stejnou hodnotu atributu druh.
Kód:: obs101
Zdroj:: Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Uveden je chybně druh komponent (počítačových souborů).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs102]]
== obs102

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Komponenty>, všechny dětské elementy <nsesss:Komponenta> se stejnou hodnotou atributu poradi obsahují v atributu verze hodnotu, která společně tvoří vzestupnou řadu přirozených čísel počínaje 1, přičemž čísla se neopakují a úvodní nuly se ignorují.
Kód:: obs102
Zdroj:: Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Uvedena je chybně verze komponent (počítačových souborů).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs103]]
== obs103

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ne a zároveň obsahuje element <nsesss:Komponenty>, ze všech dětských elementů <nsesss:Komponenta> se stejnou hodnotou atributu poradi existuje právě jeden element <nsesss:Komponenta>, který obsahuje atribut forma_uchovani s hodnotou originál.
Kód:: obs103
Zdroj:: Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Uveden je chybně originál komponent (počítačových souborů).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs104]]
== obs104

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ne a zároveň obsahuje element <nsesss:Komponenty>, ze všech dětských elementů <nsesss:Komponenta> se stejnou hodnotou atributu poradi, mezi kterými neexistuje žádný element <nsesss:Komponenta> s hodnotou atributu forma_uchovani originál ve výstupním datovém formátu, existuje právě jeden element <nsesss:Komponenta>, který obsahuje atribut forma_uchovani s hodnotou originál a současně atribut verze s hodnotou nejvyššího čísla verze.
Kód:: obs104
Zdroj:: Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Uvedena je chybně verze komponent (počítačových souborů).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs105]]
== obs105

[horizontal]

Pravidlo:: Pokud jakýkoli element <nsesss:Dokument> obsahuje v hierarchii dětských elementů <nsesss:EvidencniUdaje>, <nsesss:Manipulace> element <nsesss:AnalogovyDokument> s hodnotou ne a zároveň obsahuje element <nsesss:Komponenty>, mezi všemi dětskými elementy <nsesss:Komponenta>, v rámci kterých existuje takový element, který obsahuje atribut forma_uchovani s hodnotou originál a pro který jakýkoli element <mets:file>, který obsahuje atribut DMDID s hodnotou uvedenou v atributu ID elementu <nsesss:Komponenta> příslušné komponenty a dále atribut MIMETYPE s jednou z uvedených hodnot:
* application/msword
* application/vnd.openxmlformats-officedocument.wordprocessingml.document
* application/rtf
* application/vnd.oasis.opendocument.text
* application/vnd.apple.pages

+
existuje element <nsesss:Komponenta>, který obsahuje atribut forma_uchovani originál ve výstupním datovém formátu. Kontrola se neprovádí, pokud byla základní entita vyřízena/uzavřena do 31. 7. 2012 včetně.
Kód:: obs105
Zdroj:: § 23 odst. 2 vyhlášky č. 259/2012 Sb.; Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Uveden je chybně originál ve výstupním datovém formátu komponent (počítačových souborů).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs106]]
== obs106

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Komponenty>, ze všech dětských elementů <nsesss:Komponenta> se stejnou hodnotou atributu poradi, mezi kterými existuje jakýkoli element <nsesss:Komponenta> s hodnotou atributu forma_uchovani originál ve výstupním datovém formátu, existuje právě jeden element <nsesss:Komponenta>, který obsahuje atribut forma_uchovani s hodnotou originál ve výstupním datovém formátu a současně atribut verze s hodnotou nejvyššího čísla verze.
Kód:: obs106
Zdroj:: Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Uvedena je chybně verze originálu ve výstupním datovém formátu komponent (počítačových souborů).
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs107]]
== obs107

[horizontal]

Pravidlo:: Pokud existuje jakýkoli element <nsesss:Komponenta>, který obsahuje atribut forma_uchovani s hodnotou originál ve výstupním datovém formátu a současně atribut verze s hodnotou nejvyššího čísla verze, potom jakýkoli element <mets:file>, který obsahuje atribut DMDID s hodnotou uvedenou v atributu ID jakéhokoli elementu <nsesss:Komponenta> příslušné komponenty, obsahuje atribut MIMETYPE s jednou z uvedených hodnot:
* application/pdf
* image/png
* image/tiff
* image/jpeg
* video/mpeg
* image/gif
* audio/mpeg
* audio/x-wav
* application/xml
* application/xml-dtd

+
Kontrola se neprovádí, pokud byla základní entita vyřízena/uzavřena do 31. 7. 2012 včetně.
Kód:: obs107
Zdroj:: § 23 odst. 2 vyhlášky č. 259/2012 Sb.; Informační list NA, čá. 6/2020, č. 3/2020.
Popis chyby:: Komponenta (počítačový soubory) není ve výstupním datovém formátu.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka

[[obs108]]
== obs108

[horizontal]

Pravidlo:: Element s atributem datum obsahuje hodnotu, která po interpretaci denního data je rovna hodnotě elementu.
Kód:: obs108
Zdroj:: -
Popis chyby:: Chybně je vyplněn časový údaj.
Aktivní:: skartační řízení (jen metadata), skartační řízení (s komponentami), přejímka
