[[pouziti]]
= Použití

Validátor ZAF lze volat jako samostatnou aplikaci <<CmdValidator>> nebo
přímo integrovat do jiné Java aplikace ve formě samostatné knihovny.

[[CmdValidator]]
== Samostatný CmdValidator

Samostatný CmdValidator validátor je založen na dané verzi ZAF a 
umožňuje jeho přímé použití bez programové integrace.
Výstupem z CmdValidatoru je protokol obsahově zcela totožný 
s protokolem vytvořeným použitím zaf-core.

Validátor ZAF lze volat prostřednictvím příkazového řádku:

`java -jar CmdValidator.jar [přepínače] <path>`

*path*::
  cesta k SIPu/AIPu/XML, v případě dávkového režimu ke složce se vstupními daty


=== Přepínače

*-b|--batch*::
  Dávkový režim, vstupem je adresář obsahující SIPy

*-w|--workdir=*::
  Umístění pracovního adresáře, zde budou SIPy rozbaleny
  
*-k|--keep*::
  Zachování rozbalených souborů na disku, jinak jsou odstraněny
  
*-p|--profile=*::
  Druh kontroly pro danou validaci (AUTO - výchozí), stačí uvést druh:

 * AUTO = výběr základní kontroly pro daný typ kontroly
 * SIP_METADATA = pro provedení skartačního řízení, jen metadata bez přiložených komponent (pro NSESSS2017 a NSESSS2024)
 * SIP_PREVIEW = pro provedení skartačního řízení s přiloženými komponentami (pro NSESSS2017 a NSESSS2024)
 * SIP = pro předávání dokumentů a jejich metadat do archivu (pro NSESSS2017 a NSESSS2024)
 * AD = archivní popis (pro AP2023)
 * FA = archivní pomůcka (pro AP2023)
 * AIP = výměnný AIP (pro DAAIP2024)
 * DIP_METADATA = metadatový DIP (pro DAAIP2024)
 * DIP_CONTENT = úplný DIP (pro DAAIP2024)
 * SIP_CHANGE = změnový SIP (pro DAAIP2024)

*-e|--exclude=*::
  Seznam kontrol oddělených čárkou, které se nemají provádět
  
*-i|--id=*::
  Identifikátor prováděné kontroly
  
*-T|--threat=*::
  Podrobnosti v případě nalezení hrozby (pro předání z antivirového programu)
  
*-o|--output=*::
  Jméno souboru nebo adresáře pro uložení výsledků
  
*-t|--type=*::
  Typ validace (AUTO - výchozí)
  
 * AUTO - automatická detekce formátu vstupu
 * NSESSS2017
 * NSESSS2024
 * AP2023
 * DAAIP2024
 
*-f|--format=*::
  Výstupní formát (XML_V2 - výchozí)
  
 * XML_V2 = obecné schéma (link:validation_v2.xsd[validation_v2.xsd])
 * XML_V1 = obecné české schéma (link:validace_v1.xsd[validace_v1.xsd])
 * XML_OLD = schéma pouze pro kontrolu NSESSS
 

[[ZafSystParametry]]
== Systémové parametry

Pokročilé funkce validátoru je možné řídit pomocí systémových parametrů (parametr *-D*).

*zaf.vera.servermode*::
  Určuje, zda se validátor použije v serverovém režimu nebo je vždy samostatně
  spouštěn pro každý jednotlivý běh. Přípustné hodnoty jsou *true* | *false*. 
  Ve výchozím režimu se použije serverový režim.
  
*zaf.vera.path*::
  Cesta k lokální instalaci VeraPDF validátoru. Jedná se o úplnou cestu k .jar souboru
  včetně tohoto souboru. Pokud není nastaveno, použije se verze validátoru vestavěná 
  přímo do aplikace.
  
*zaf.vera.timeout*::
  Určení maximální doby běhu validátoru v minutách. Výchozí hodnota je 5 minut.

*zaf.vera.jvm.params*::
  Dodatečné volby pro JVM v němž je spuštěn validátor VeraPDF. Volbu například použít 
  pro nastavení maximální velikosti paměti dostupné pro validátor.
  Příklad:
   
  `-Dzaf.vera.jvm.params=-Xmx1g`

*zaf.vera.profile*::
  Cesta k vlastnímu validačnímu profilu VeraPDF (XML). Pokud je nastavena,
  je validátor VeraPDF spuštěn s volbou `--profile` a validace probíhá výhradně
  proti tomuto profilu namísto výchozí sady profilů. Příklad:

  `-Dzaf.vera.profile=C:\profily\custom-profile.xml`

*zaf.vera.params*::
  Dodatečné volby předané validátoru VeraPDF na příkazové řádce.
  Volby `--format` a `--servermode` jsou vyhrazeny pro ZAF a nelze je
  touto cestou měnit. Hodnoty obsahující mezery je nutné uzavřít do uvozovek.
  Příklad:

  `-Dzaf.vera.params="--profile /adresar/profily/custom-profile.xml"`

*zaf.siegfried.path*::
  Úplná cesta ke spustitelnému souboru aplikace SiegFried. Pokud je cesta nastavena 
  použije se tato aplikace pro ověření správnosti mimeType viz 
  xref:k07-komponenty.adoc#kom3[pravidlo kom3]. Příklad:
   
  `-Dzaf.siegfried.path=C:\toolkits\zaf\sf\sf.exe`

*zaf.siegfried.port*::
  Volitelný parametr pro určení portu, který má být využit aplikací SiegFried.
  Výchozí hodnota je port *20000*. Port nesmí být obsazen jiným procesem jinak není 
  možné SiegFried spustit.

*zaf.zip.encoding*::
  Nastavení výchozího kódování pro rozbalování ZIP souborů. Jako výchozí kódování
  je nastaveno *UTF-8*. Dříve se v českém prostředí využívalo jako primární kódování
  *IBM852*. 


[[pouziti_priklady]]
=== Příklady volání

Validace jednotlivého SIPu se zápisem výstupu do protokolu:

`java -jar CmdValidator.jar -p SIP C:\testy3\D34520.zip -o c:\temp\out.xml`


Validace SIPů uložených v adresáři:

`java -jar CmdValidator.jar -b "C:\temp\SIP1580724295329"`


Validace SIPů uložených v adresáři s využitím jiné verze VeraPDF:

`java -Dzaf.vera.path=C:\verapdf\cli.jar -jar CmdValidator.jar -p SIP -b "C:\temp\SIP1580724295329"`


[[pouziti_schema_xsd]]
== Výsledek validace

Výsledkem validace je XML dokument. Ve výchozím nastavení je vytvořen podle
XSD schématu link:validation_v2.xsd[validation_v2.xsd] (formát `XML_V2`).

Přepínačem xref:pouziti.adoc#pouziti[`-f|--format`] lze zvolit i starší schémata:

* `XML_V1` – link:validace_v1.xsd[validace_v1.xsd], české obecné schéma,
* `XML_OLD` – link:validaceSIP.xsd[validaceSIP.xsd], nejstarší schéma použitelné
  pouze pro typy validace NSESSS2017 a NSESSS2024.

Výsledný dokument obsahuje:

* informaci o verzi validátoru a aplikace provádějící kontrolu
* typ validace a použitý profil pravidel
* verzi pravidel podle níž kontrola proběhla
* jednotlivé vrstvy kontrol a jejich výsledek (`OK`, `ERROR`, `NOT_EXECUTED`)
* pravidla, s nimiž vstup není v souladu, a to včetně:
** podrobného popisu pravidla
** kódu pravidla
** zdroje pravidla
** kódu chyby
** popisu chyby
** výpisu chyby
** odkazu do XML na místo chyby
** identifikace entit, které jsou chybné

Vrstva, která nebyla provedena, protože kontrola skončila již v některé
z předchozích vrstev, je uvedena se stavem `NOT_EXECUTED`.

=== Příklad výsledku validace bez chyb
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<validation xmlns="https://stands.nacr.cz/validation_zaf/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://stands.nacr.cz/validation_zaf/v2 https://stands.nacr.cz/validation_zaf/v2/validation_v2.xsd"
    validationIdentifier="0dedc85e-839b-4659-b762-fca760299fbc"
    applicationName="ZAF" applicationVersion="2.0.0" validationType="NSESSS2017"
    validationProfile="přejímka" rulesVersion="6"
    validationTimestamp="2025-09-12T16:11:32.011176700Z">
    <package fileName="01-OK" identifier="GS_ea183e38-a932-4a68-bb16-4a7871ab56a7">
        <check name="škodlivého kódu" status="OK"/>
        <check name="datové struktury" status="OK"/>
        <check name="znakové sady" status="OK"/>
        <check name="správnosti XML" status="OK"/>
        <check name="jmenných prostorů" status="OK"/>
        <check name="proti schématu" status="OK"/>
        <check name="kontrola obsahu" status="OK"/>
        <check name="kontrola komponent" status="OK"/>
    </package>
</validation>
----

=== Příklad výsledku validace s chybou
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<validation xmlns="https://stands.nacr.cz/validation_zaf/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://stands.nacr.cz/validation_zaf/v2 https://stands.nacr.cz/validation_zaf/v2/validation_v2.xsd"
    validationIdentifier="ebd99d48-e26f-4db4-b42d-5c8325931904"
    applicationName="ZAF" applicationVersion="2.0.0" validationType="NSESSS2017"
    validationProfile="přejímka" rulesVersion="6"
    validationTimestamp="2025-09-12T16:12:49.560197500Z">
    <package fileName="104-chyba1" identifier="GS_ea183e38-a932-4a68-bb16-4a7871ab56a7">
        <check name="škodlivého kódu" status="OK"/>
        <check name="datové struktury" status="OK"/>
        <check name="znakové sady" status="OK"/>
        <check name="správnosti XML" status="OK"/>
        <check name="jmenných prostorů" status="OK"/>
        <check name="proti schématu" status="OK"/>
        <check name="kontrola obsahu" status="ERROR">
            <rule>
                <code>obs104</code>
                <text>Pokud jakýkoli element &lt;nsesss:Dokument> obsahuje v hierarchii dětských elementů &lt;nsesss:EvidencniUdaje>, &lt;nsesss:Manipulace> element &lt;nsesss:AnalogovyDokument> s hodnotou ne a zároveň obsahuje element &lt;nsesss:Komponenty>, ze všech dětských elementů &lt;nsesss:Komponenta> se stejnou hodnotou atributu poradi, mezi kterými neexistuje žádný element &lt;nsesss:Komponenta> s hodnotou atributu forma_uchovani originál ve výstupním datovém formátu, existuje právě jeden element &lt;nsesss:Komponenta>, který obsahuje atribut forma_uchovani s hodnotou originál a současně atribut verze s hodnotou nejvyššího čísla verze.</text>
                <source>Informační list NA, čá. 6/2020, č. 3/2020.</source>
                <errorCode>CHYBA</errorCode>
                <errorDescription>Uvedena je chybně verze komponent (počítačových souborů).</errorDescription>
                <errorReport>Komponenta s formou uchování originál nemá nejvyšší číslo verze, pozice: 1, nejvyšší číslo verze: 3, číslo verze originálu: 2</errorReport>
                <errorLocation>Řádek 17:44, element &lt;nsesss:Dokument>.</errorLocation>
                <entity>
                    <identifier type="DOKUMENT" source="Gordic.Ginis.MP12.X">MP12P00BTZ3Z</identifier>
                </entity>
            </rule>
        </check>
        <check name="kontrola komponent" status="NOT_EXECUTED"/>
    </package>
</validation>
----

[[ZafKnihovna]]
== Java knihovna - přímá integrace
Validátor ZAF je možné volat jako součást jiné Java aplikace a integrovat ho s ní. Pokud není možná
přímá integrace lze použít xref:pouziti.adoc#CmdValidator[řádkovou aplikaci CmdValidator].

V rámci https://github.com/validatorzaf/zaf[projektu na GitHub.com] jsou k dispozici zdrojové kódy aplikace a binární balíčky. 
Ty jsou také dostupné v repozitáři pro Maven a je možné je přímo používat.

=== Maven (pom.xml)

[source,xml,subs="attributes+"]
----
  <dependency>
    <groupId>cz.zaf</groupId>
    <artifactId>zaf-core</artifactId>
    <version>{zafVersion}</version>
  </dependency>
----

=== Repozitář s připravenými balíčky

Validátor ZAF je možné přímo využívat pomocí připravených balíčků 
dostupných v repozitáři: https://pkgs.lightcomp.com/maven/public-release/.

Nastavení pro Maven (pom.xml):

[source,xml]
----
  <repositories>
    <repository>
      <id>lc-public-release</id>
      <url>https://pkgs.lightcomp.com/maven/public-release/</url>
    </repository>
  </repositories>
----


[[pouziti_logovani]]
== Možnosti logování
Pro logování činnosti aplikace je využíván nástroj https://www.slf4j.org/[SLF4J]. 
Konkrétní nastavení logování záleží na způsobu využití nástroje ZAF. Pokud je používán jako 
řádková aplikace je jeho součástí SimpleLogger. Možnosti jeho nastavení jsou uvedeny v 
https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html[dokumentaci k SLF4J/SimpleLogger].

[[pouziti_logovani_priklady]]
=== Spuštění s logováním vnitřní činnosti

Spuštění s logováním vnitřní činnosti slouží pro diagnostické účely.

Příklad:

`java -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG -jar CmdValidator.jar -p SIP C:\testy3\D34520.zip -o c:\temp\out.xml`
