[[pouziti]]
= Použití

Validátor ZAF lze volat jako samostatnou aplikaci <<CmdValidator>> nebo
přímo integrovat do jiné Java aplikace ve formě samostatné knihovny.

[[CmdValidator]]
== Samostatný CmdValidator

Samostatný CmdValidator validátor je založen na dané verzi ZAF a 
umožňuje jeho přímé použití bez programové integrace.
Výstupem z CmdValidatoru je protokol obsahově zcela totožný 
s protokolem vytvořeným použitím zaf-core.

Validátor ZAF lze volat prostřednictvím příkazového řádku:

`java -jar CmdValidator.jar [přepínače] <path>`

*path*::
  cesta k SIPu, v případě dávkového režimu ke složce se SIPy


=== Přepínače

*-b|--batch*::
  Dávkový režim, vstupem je adresář obsahující SIPy

*-w|--workdir=*::
  Umístění pracovního adresáře, zde budou SIPy rozbaleny
  
*-d|--druh=*::
  Druh validace (1 - výchozí):

 * 1 = pro provedení skartačního řízení (jen metadata bez přiložených komponent)
 * 2 = pro provedení skartačního řízení (s přiloženými komponentami)
 * 3 = pro předávání dokumentů a jejich metadat do archivu

*-e|--exclude=*::
  Seznam kontrol oddělených čárkou, které se nemají provádět
  
*-i|--id=*::
  Identifikátor prováděné kontroly
  
*-z|--hrozba=*::
  Podrobnosti v případě nalezení hrozby (pro předání z antivirového programu)
  
*-o|--output=*::
  Jméno souboru nebo adresáře pro uložení výsledků


=== Systémové parametry

Pokročilé funkce validátoru je možné řídit pomocí systémových parametrů (parametr *-D*).

*zaf.vera.servermode*::
  Určuje, zda se validátor použije v serverovém režimu nebo je vždy samostatně
  spouštěn pro každý jednotlivý běh. Přípustné hodnoty jsou *true* | *false*. 
  Ve výchozím režimu se použije serverový režim.
  
*zaf.vera.path*::
  Cesta k lokální instalaci VeraPDF validátoru. Jedná se o úplnou cestu k .jar souboru
  včetně tohoto souboru. Pokud není nastaveno, použije se verze validátoru vestavěná 
  přímo do aplikace.
 


[[pouziti_priklady]]
=== Příklady volání

Validace jednotlivého SIPu se zápisem výstupu do protokolu:

`java -jar CmdValidator.jar -d 3 C:\testy3\D34520.zip -o c:\temp\out.xml`


Validace SIPů uložených v adresáři:

`java -jar CmdValidator.jar -b "C:\temp\SIP1580724295329"`


Validace SIPů uložených v adresáři s využitím jiné verze VeraPDF:

`java -Dzaf.vera.path=C:\verapdf\greenfield-apps.jar -jar CmdValidator.jar -d 3 -b "C:\temp\SIP1580724295329"`



[[pouziti_schema_xsd]]
== Výsledek validace
Výsledkem validace je XML dokument. Ten je vytvořen dle XSD schématu link:validace.xsd[validace.xsd].

Výsledný dokument obsahuje:

* informaci o verzi validátoru a aplikace provádějící kontrolu
* verze pravidel podle níž kontrola proběhla
* jednotlivé typy kontrol a jejich výsledek
* pravidla s nímž SIP není v souladu a to včetně:
** podrobného popisu pravidla
** kódu pravidla
** kódu chyby
** popisu chyby
** odkazu do XML na místo chyby
** identifikaci entit, které jsou chybné

=== Příklad výsledku validace bez chyb
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<validaceSIP xmlns="http://www.ahmp.cz/schema/validacesip/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ahmp.cz/schema/validacesip/v1 http://www.ahmp.cz/schema/validacesip/v1/validace.xsd" 
    validaceID="54f6480d-4e71-4f75-bd49-885b1edd8277" 
    nazevAplikace="zaf-core" verzeAplikace="0.9.4" verzePravidel="1" 
    datumValidace="2022-02-05T01:37:36.660Z" druhValidace="přejímka">
    <sip nazevSouboru="D34520.zip" OBJID="399">
        <kontrola nazev="škodlivého kódu" stav="ok"/>
        <kontrola nazev="datové struktury" stav="ok"/>
        <kontrola nazev="znakové sady" stav="ok"/>
        <kontrola nazev="správnosti XML" stav="ok"/>
        <kontrola nazev="jmenných prostorů" stav="ok"/>
        <kontrola nazev="souladu se schématem XSD" stav="ok"/>
        <kontrola nazev="kontrola obsahu" stav="ok"/>
    </sip>
</validaceSIP>
----

=== Příklad výsledku validace s chybou
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<validaceSIP xmlns="http://www.ahmp.cz/schema/validacesip/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ahmp.cz/schema/validacesip/v1 http://www.ahmp.cz/schema/validacesip/v1/validace.xsd" 
    validaceID="a5b381e5-f3b7-4663-ab70-91b3b89fe8fb" 
    nazevAplikace="zaf-core" verzeAplikace="0.9.4" verzePravidel="1" 
    datumValidace="2022-02-05T01:32:05.946Z" druhValidace="skartační řízení (jen metadata)">
    <sip nazevSouboru="SIP1580724295329" OBJID="1580724294814">
        <kontrola nazev="škodlivého kódu" stav="ok"/>
        <kontrola nazev="datové struktury" stav="ok"/>
        <kontrola nazev="znakové sady" stav="ok"/>
        <kontrola nazev="správnosti XML" stav="ok"/>
        <kontrola nazev="jmenných prostorů" stav="ok"/>
        <kontrola nazev="souladu se schématem XSD" stav="ok"/>
        <kontrola nazev="kontrola obsahu" stav="chyba">
            <pravidlo>
                <kod>obs39</kod>
                <zneni>Každý element &lt;mets:digiprovMD&gt; obsahuje v hierarchii dětských elementů &lt;mets:mdWrap&gt;, &lt;mets:xmlData&gt; právě jeden dětský element &lt;tp:TransakcniLogObjektu&gt;.</zneni>
                <zdroj>Bod 2.12. přílohy č. 3 NSESSS.</zdroj>
                <kodChyby>CHYBA</kodChyby>
                <popisChyby>Datový balíček SIP neobsahuje transakční protokol.</popisChyby>
                <vypisChyby>Element &lt;mets:xmlData> neobsahuje žádný dětský element &lt;tp:TransakcniLogObjektu&gt;.</vypisChyby>
                <mistoChyby>Řádek 234:23, element &lt;mets:xmlData&gt;.</mistoChyby>
            </pravidlo>
            <pravidlo>
                <kod>obs54</kod>
                <zneni>Pokud neexistuje žádný element &lt;nsesss:KrizovyOdkaz&gt; s atributem pevny s hodnotou ano, potom každý element &lt;mets:div&gt; obsahuje dětský element podle struktury entit/objektů (od spisového plánu po komponentu) v sekci dmdSec s atributem TYPE s hodnotou příslušné entity/objektu a s atributem DMDID s hodnotou příslušné entity/objektu v atributu ID a s atributem ADMID s hodnotou, která odpovídá hodnotě atributu ID příslušné entity/objektu v sekci amdSec (entita/objekt v hierarchii dětských elementů &lt;mets:digiprovMD&gt;, &lt;mets:mdWrap&gt;, &lt;mets:xmlData&gt;, &lt;tp:TransakcniLogObjektu&gt;, &lt;tp:TransLogInfo&gt;, &lt;tp:Objekt&gt;, &lt;tp:Identifikator&gt;, &lt;tns:HodnotaID&gt; a &lt;tns:ZdrojID&gt; odpovídá v hodnotách hodnotám elementu &lt;nsesss:Identifikator> a jeho atributu zdroj příslušné entity/objektu v sekci dmdSec).</zneni>
                <zdroj>Bod 2.17 a 2.18. přílohy č. 3 NSESSS; Informační list NA, roč. 2018, čá. 2, příloha k č. 20/2018 (20.3).</zdroj>
                <kodChyby>CHYBA</kodChyby>
                <popisChyby>Chybí spisový plán, věcná skupina, typový spis, součást, díl, spis, dokument nebo komponenta ve strukturální mapě a jejich provázání na transakční protokol.</popisChyby>
                <vypisChyby>Nenalezen element tns:HodnotaID v sekci mets:amdSec.</vypisChyby>
                <mistoChyby>Řádek 600:41, element &lt;mets:amdSec&gt;.</mistoChyby>
            </pravidlo>
        </kontrola>
    </sip>
</validaceSIP>
----

== Java knihovna - přímá integrace
Validátor ZAF je možné volat jako součást jiné Java aplikace a integrovat ho s ní. Pokud není možná
přímá integrace lze použít :xref:pouziti.adoc#CmdValidator[řádkovou aplikaci CmdValidator].

V rámci projektu na GitHub.com jsou k dispozici zdrojové kódy aplikace a binární balíčky. 
Ty jsou také dostupné v repozitáři pro Maven a je možné je přímo používat.

=== Maven (pom.xml)

[source,xml,subs="attributes+"]
----
  <dependency>
    <groupId>cz.zaf</groupId>
    <artifactId>zaf-core</artifactId>
    <version>{zafVersion}</version>
  </dependency>
----

=== Repozitář s připravenými balíčky

Validátor ZAF je možné přímo využívat pomocí připravených balíčků 
dostupných v repozitáři: https://www.lightcomp.cz/releases/repository/lc-public-release/.

Nastavení pro Maven (pom.xml):

[source,xml]
----
  <repositories>
    <repository>
      <id>lc-public-release</id>
      <url>https://www.lightcomp.cz/releases/repository/lc-public-release/</url>
    </repository>
  </repositories>
----


[[pouziti_logovani]]
== Možnosti logování
Pro logování činnosti aplikace je využíván nástroj https://www.slf4j.org/[SLF4J]. 
Konkrétní nastavení logování záleží na způsobu využití nástroje ZAF. Pokud je používán jako 
řádková aplikace je jeho součástí SimpleLogger. Možnosti jeho nastavení jsou uvedeny v 
https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html[dokumentaci k SLF4J/SimpleLogger].

[[pouziti_logovani_priklady]]
=== Spuštění s logováním vnitřní činnosti

Spuštění s logováním vnitřní činnosti slouží pro diagnostické účely.

Příklad:

`java -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG -jar CmdValidator.jar -d 3 C:\testy3\D34520.zip -o c:\temp\out.xml`
