/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zaf.sipvalidui.panels;

import java.awt.Dimension;

import javax.swing.ListSelectionModel;



/**
 *
 * @author m000xz006159
 */
public class JPanelValidace extends javax.swing.JPanel {

    /**
     * Creates new form JPanelvalidace
     */
    public JPanelValidace(NahraneSoubory nahraneSoubory) {
        initComponents();
        jSplitPane1.getLeftComponent().setPreferredSize(new Dimension(150, 200));
        jListObsahovaNA.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModel listSelection3 = jListObsahovaNA.getSelectionModel();
        
        listSelection3.addListSelectionListener(new EventListenerJpanelValidaceListObsahovaNa(jTextAreaPopisPravidel,
                jListObsahovaNA, nahraneSoubory));
        jCheckBoxObsahovaNa.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jListObsahovaNA = new javax.swing.JList();
        jCheckBoxObsahovaNa = new javax.swing.JCheckBox();
        jLabelColorSpolecna = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaPopisPravidel = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaPredKontrola = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setViewportView(jListObsahovaNA);

        jLabelColorSpolecna.setBackground(new java.awt.Color(255, 255, 255));
        jLabelColorSpolecna.setText("OBSAHOVÁ");
        jLabelColorSpolecna.setOpaque(true);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTextAreaPopisPravidel.setEditable(false);
        jTextAreaPopisPravidel.setColumns(20);
        jTextAreaPopisPravidel.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaPopisPravidel.setLineWrap(true);
        jTextAreaPopisPravidel.setRows(5);
        jTextAreaPopisPravidel.setWrapStyleWord(true);
        jTextAreaPopisPravidel.setAutoscrolls(false);
        jTextAreaPopisPravidel.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextAreaPopisPravidel.setMinimumSize(new java.awt.Dimension(200, 200));
        jTextAreaPopisPravidel.setName(""); // NOI18N
        jTextAreaPopisPravidel.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane5.setViewportView(jTextAreaPopisPravidel);

        jSplitPane1.setTopComponent(jScrollPane5);

        jTextAreaPredKontrola.setColumns(20);
        jTextAreaPredKontrola.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaPredKontrola.setRows(5);
        jTextAreaPredKontrola.setText(" \n");
        jTextAreaPredKontrola.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane3.setViewportView(jTextAreaPredKontrola);

        jSplitPane1.setRightComponent(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelColorSpolecna, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jCheckBoxObsahovaNa))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxObsahovaNa)
                            .addComponent(jLabelColorSpolecna, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox jCheckBoxObsahovaNa;
    public static javax.swing.JLabel jLabelColorSpolecna;
    public static javax.swing.JList jListObsahovaNA;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    public static javax.swing.JTextArea jTextAreaPopisPravidel;
    public static javax.swing.JTextArea jTextAreaPredKontrola;
    // End of variables declaration//GEN-END:variables
}
