/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipvalid.frames.panels;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author m000xz006159
 */
public class JPanelSkartacniNavrh extends javax.swing.JPanel {
    private final DefaultTableModel skartacniNavrhTableModel;
    /**
     * Creates new form JPanelSkartacniNavrh
     */
    public JPanelSkartacniNavrh() {
        initComponents();
        skartacniNavrhTableModel = new DefaultTableModel();
        nastavTabulku(skartacniNavrhTableModel, jTable1);
    }
    
    private void nastavTabulku(DefaultTableModel model, JTable table){
        // nutno vždy nastavit počet sloupců
        table.setModel(model);
        int i = jTable1.getWidth();
        Dimension d = new Dimension();
        d = table.getPreferredScrollableViewportSize();
        int z = d.width;
        model.setColumnCount(11);
        // zarovnání textu do středu
        DefaultTableCellRenderer defTableCellRendererCenterAlighment = new DefaultTableCellRenderer();
        defTableCellRendererCenterAlighment.setHorizontalAlignment(SwingConstants.CENTER);         
        // sloupec 1.
        setColumnHeader(table, "Poř.č.", 0, 40, 40, 0);
        table.getColumnModel().getColumn(0).setCellRenderer(defTableCellRendererCenterAlighment);
        // sloupec 2.
        setColumnHeader(table, "Sp. plán", 1, 100, 50, 50);
        // sloupec 3.
        setColumnHeader(table, "A/D", 2, 30, 30, 0);
        table.getColumnModel().getColumn(2).setCellRenderer(defTableCellRendererCenterAlighment);
        
        // sloupec 4.
        setColumnHeader(table, "TYP", 3, 30, 30, 0);
        table.getColumnModel().getColumn(3).setCellRenderer(defTableCellRendererCenterAlighment);
        // sloupec 5.
        setColumnHeader(table, "Sp. znak", 4, 100, 55, 55);
        // sloupec 6. 
        setColumnHeader(table, "Název", 5, 0, 0, z);
        // sloupec 7.
        setColumnHeader(table, "Ukládací Jednotka", 6, 150, 100, 100);
        // sloupec 8.
        setColumnHeader(table, "Sk. režim", 7, 55, 55, 0);
        table.getColumnModel().getColumn(7).setCellRenderer(defTableCellRendererCenterAlighment);
        // sloupec 9.
        setColumnHeader(table, "Časový rozsah", 8, 85, 85, 0);
        table.getColumnModel().getColumn(8).setCellRenderer(defTableCellRendererCenterAlighment);
        // sloupec 10.
        setColumnHeader(table, "Počítadlo", 9, 100, 100, 0);
        // sloupec 11.
        setColumnHeader(table, "", 10, 30, 30, 0);
        table.getColumnModel().getColumn(10).setHeaderValue("X");
        table.getColumnModel().getColumn(10).setCellRenderer(defTableCellRendererCenterAlighment);
        
       
        // speciální nastavení pro jTable
        // dvojí kliknutí na tableHeader
//        jTable1.getTableHeader().addMouseListener(new MouseAdapter() {
//            @Override
//            public void mouseClicked(MouseEvent e){
//                if(e.getClickCount() == 2){
//                    int col = jTable1.columnAtPoint(e.getPoint()); // získá na jaký sloupec jsem klikl
//                    System.err.println(col);
//                }    
//            }           
//        });
        
    }
    
    // pomocná metoda pro nastavení celého sloupce
    private void setColumnHeader(JTable table, String nazev, int columnIndex, int maxWidth, int minWidth, int prefWidth){    
        // nastavení názvu hlavičky sloupce
        table.getColumnModel().getColumn(columnIndex).setHeaderValue(nazev);
        // nastavení velikostí width (0 znamená že nechci tuto hodnotu nastavovat)
        if(maxWidth != 0) table.getColumnModel().getColumn(columnIndex).setMaxWidth(maxWidth);
        if(minWidth != 0) table.getColumnModel().getColumn(columnIndex).setMinWidth(minWidth);
        if(prefWidth != 0) table.getColumnModel().getColumn(columnIndex).setPreferredWidth(prefWidth);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Poznámka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZNAK A", "ZNAK S", "ZNAK V", "ZNAK X" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        for(int i = 0; i < 100000; i++){
            Object[] o = new Object[]{(i+1) + ".", " Položka klasifikace (2016–3000)", "A", "SPI", " 01.01.07", " Guvernér a členové bankovní rady --> Dokumenty obecného charakteru Dokumenty obecného charakteru Dokumenty obecného charakteru Dokumenty obecného charakterub ultra nové rozhodnutí ředitele ultra nové rozhodnutí řediteleultra nové rozhodnutí řediteleultra nové rozhodnutí řediteleultra nové rozhodnutí ředitele HOVNO", " jednotka uložiště", "A 5", "2016-2020", " 20/10/0", "X"};
            skartacniNavrhTableModel.addRow(o);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
