[[NSESSS2024_novezmeny]]
= Změny v pravidlech

== v1, 9.10.2025

* Přidána základní sada pravidel pro archivní pomůcky

== v2, 25.3.2026

* Dokončená úplná sada pravidel nsesss2024

== v3, 24.4.2026

* Odstraněn profil vývojářské validace; pravidla jsou nyní uplatňována pouze v profilech skartačního řízení a přejímky
* Odstraněno pravidlo obs9 (chybně zařazené pravidlo)
* Upraveno znění pravidla dat1a
* Přepracováno pravidlo obs64 – kontrola se nově provádí pro všechny základní entity (dokument, díl i spis) a porovnává součet roku spouštěcí události, skartační lhůty a roku vyřazení vůči aktuálnímu roku
* Úpravy zařazení pravidel obs86, obs92 a obs94
* Textové úpravy znění pravidel (zejména obs54, obs96 a kom1–kom3)

== v4, 16.9.2026

* Nová pravidla <<NSESSS2024_obs63a,obs63a>>, <<NSESSS2024_obs63b,obs63b>> a <<NSESSS2024_obs63c,obs63c>> – kontrola, že rok vyřízení dokumentu, vyřízení/uzavření spisu a uzavření dílu je nižší než aktuální rok
* Změna pravidla <<NSESSS2024_obs59a,obs59a>> – evidenční číslo se nevyžaduje u dokumentu, který obsahuje element <nsesss:Neevidence>
* Změna pravidla <<NSESSS2024_obs66,obs66>> – shodný skartační znak se nově vyžaduje i u dokumentů zatříděných do spisu nebo dílu, pokud byla rodičovská entita vyřízena/uzavřena po 31. 12. 2026
* Textové úpravy znění pravidel obs59a a obs66 podle výše uvedených změn
